services:
  pollord-backend:
    image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG:-latest}
    container_name: pollord-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - pollord-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  pollord-network:
    external: true
    name: pollord-network
