"""add payout recipient and transfer fields

Revision ID: 21fbf74929c3
Revises: e0affcdee83b
Create Date: 2026-08-12 01:18:06.525810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fbf74929c3'
down_revision: Union[str, None] = 'e0affcdee83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payout_requests', sa.Column('payout_method', sa.String(length=20), nullable=True))
    op.add_column('payout_requests', sa.Column('recipient_name', sa.String(length=255), nullable=True))
    op.add_column('payout_requests', sa.Column('mobile_network', sa.String(length=20), nullable=True))
    op.add_column('payout_requests', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('payout_requests', sa.Column('paystack_recipient_code', sa.String(length=100), nullable=True))
    op.add_column('payout_requests', sa.Column('transfer_reference', sa.String(length=100), nullable=True))
    op.add_column('payout_requests', sa.Column('transfer_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payout_requests', 'transfer_status')
    op.drop_column('payout_requests', 'transfer_reference')
    op.drop_column('payout_requests', 'paystack_recipient_code')
    op.drop_column('payout_requests', 'mobile_number')
    op.drop_column('payout_requests', 'mobile_network')
    op.drop_column('payout_requests', 'recipient_name')
    op.drop_column('payout_requests', 'payout_method')
    # ### end Alembic commands ###
