"""add ticket_transactions

Revision ID: b0dae0f4a2eb
Revises: 62c1756c2dee
Create Date: 2026-08-09 15:34:17.820067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0dae0f4a2eb'
down_revision: Union[str, None] = '62c1756c2dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paystack_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_ticket_transactions_event_id'), 'ticket_transactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_ticket_transactions_reference'), 'ticket_transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_ticket_transactions_status'), 'ticket_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_transactions_user_id'), 'ticket_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_transactions_user_id'), table_name='ticket_transactions')
    op.drop_index(op.f('ix_ticket_transactions_status'), table_name='ticket_transactions')
    op.drop_index(op.f('ix_ticket_transactions_reference'), table_name='ticket_transactions')
    op.drop_index(op.f('ix_ticket_transactions_event_id'), table_name='ticket_transactions')
    op.drop_table('ticket_transactions')
    # ### end Alembic commands ###
