"""add guest ticket fields

Revision ID: d48840316887
Revises: b0dae0f4a2eb
Create Date: 2026-08-09 18:45:40.259943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48840316887'
down_revision: Union[str, None] = 'b0dae0f4a2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_purchases', sa.Column('guest_name', sa.String(length=255), nullable=True))
    op.add_column('ticket_purchases', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.add_column('ticket_purchases', sa.Column('guest_phone', sa.String(length=50), nullable=True))
    op.alter_column('ticket_purchases', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('ticket_transactions', sa.Column('guest_name', sa.String(length=255), nullable=True))
    op.add_column('ticket_transactions', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.add_column('ticket_transactions', sa.Column('guest_phone', sa.String(length=50), nullable=True))
    op.alter_column('ticket_transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('tickets', sa.Column('guest_name', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('guest_phone', sa.String(length=50), nullable=True))
    op.alter_column('tickets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)

    # Autogenerate doesn't pick up CHECK constraints — added by hand.
    op.create_check_constraint(
        'ck_ticket_purchases_owner_present',
        'ticket_purchases',
        'user_id IS NOT NULL OR guest_email IS NOT NULL',
    )
    op.create_check_constraint(
        'ck_ticket_transactions_owner_present',
        'ticket_transactions',
        'user_id IS NOT NULL OR guest_email IS NOT NULL',
    )
    op.create_check_constraint(
        'ck_tickets_owner_present',
        'tickets',
        'user_id IS NOT NULL OR guest_email IS NOT NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tickets_owner_present', 'tickets', type_='check')
    op.drop_constraint('ck_ticket_transactions_owner_present', 'ticket_transactions', type_='check')
    op.drop_constraint('ck_ticket_purchases_owner_present', 'ticket_purchases', type_='check')

    op.alter_column('tickets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tickets', 'guest_phone')
    op.drop_column('tickets', 'guest_email')
    op.drop_column('tickets', 'guest_name')
    op.alter_column('ticket_transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ticket_transactions', 'guest_phone')
    op.drop_column('ticket_transactions', 'guest_email')
    op.drop_column('ticket_transactions', 'guest_name')
    op.alter_column('ticket_purchases', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ticket_purchases', 'guest_phone')
    op.drop_column('ticket_purchases', 'guest_email')
    op.drop_column('ticket_purchases', 'guest_name')
    # ### end Alembic commands ###
