"""add token_version and login lockout fields to users

Revision ID: e83ade0c9c9e
Revises: d4e8b2f6a1c9
Create Date: 2026-09-09 00:47:33.424350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83ade0c9c9e'
down_revision: Union[str, None] = 'd4e8b2f6a1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Note: unrelated ussd_code index/constraint drift (pre-existing, from an
    # earlier migration) was intentionally excluded from this autogenerated
    # revision to keep it scoped to the auth hardening changes below.
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'token_version')
