"""add refresh_tokens table for rotation and reuse detection

Revision ID: eca0d327674c
Revises: e83ade0c9c9e
Create Date: 2026-09-09 00:57:09.190587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca0d327674c'
down_revision: Union[str, None] = 'e83ade0c9c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Note: unrelated ussd_code index/constraint drift (pre-existing, from an
    # earlier migration) was intentionally excluded from this autogenerated
    # revision to keep it scoped to the auth hardening changes below.
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('idx_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)


def downgrade() -> None:
    op.drop_index('idx_refresh_token_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
